version: '3.4'

services:
  upload-checker-server:
    image: upload-checker:latest
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000"]
    ports:
      - 5678:5678
